openapi: '3.1.0'
info:
  title: Hotel Management System
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://hotel-management-api-project.onrender.com
    description: Render deployment
tags:
  - name: Authentication
    descripion: Login-related endpoints
  - name: Users
    description: User-related endpoints
  - name: Rooms
    description: Room-related endpoints
  - name: Services
    description: Service-related endpoints
  - name: Bookings
    description: Booking related endpoints
paths:
  /auth/login:
    $ref: paths/authentication.yaml
  /users:
    $ref: ./paths/users.yaml
  /users/{id}:
    $ref: ./paths/userID.yaml
  /rooms:
    $ref: ./paths/rooms.yaml
  /rooms/{id}:
    $ref: ./paths/roomID.yaml
  /services:
    $ref: ./paths/services.yaml
  /services/{id}:
    $ref: ./paths/serviceID.yaml
  /bookings:
    $ref: ./paths/bookings.yaml
  /bookings/{id}:
    $ref: ./paths/bookingsID.yaml
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
